version: '3'

services:
    app:
      build: .
      container_name: book_class_app
      volumes:
          - .:/var/www
          - ./.docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      depends_on:
          - db

    nginx:
      build: .docker/nginx
      container_name: book_class_nginx
      restart: always
      tty: true
      ports:
          - "8000:80"
      volumes:
          - .:/var/www
      depends_on:
          - app

    db:
      build: ./.docker/mysql
      container_name: book_class_db
      restart: always
      tty: true
      ports:
          - "33006:3306"
      volumes:
          - ./.docker/dbdata:/var/lib/mysql
          - ./.docker/mysql:/docker-entrypoint-initdb.d
      environment:
          - MYSQL_DATABASE=db
          - MYSQL_ROOT_PASSWORD=root