openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/classes:
    get:
      summary: ''
      operationId: getApiClasses
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Classes retrieved successfully!'
                  total: 5
                  nextPageUrl: ''
                  content:
                    -
                      id: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                      name: 'Classe updated'
                      description: 'Descrição teste'
                      start_date: 02/09/2023
                      end_date: 10/12/2023
                      capacity: 30
                      bookings:
                        -
                          id: 0a3aaca2-4435-4d9c-a075-ee90b0ca8f97
                          class_id: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                          name: Gabriel
                          date: 11/11/2023
                        -
                          id: 5b0c85de-e1a6-4876-b409-b1b886588fd1
                          class_id: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                          name: Gabriel
                          date: 11/11/2023
                        -
                          id: bf5c029c-d20a-4635-ad26-9c7b6efa8f26
                          class_id: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                          name: Gabriel
                          date: 11/11/2023
                    -
                      id: a094d309-6974-405b-8559-fe0f4684c92c
                      name: 'Classe teste'
                      description: 'Descrição teste'
                      start_date: 02/09/2023
                      end_date: 10/12/2023
                      capacity: 30
                      bookings: []
                    -
                      id: ee440f38-073a-426f-885d-6a9a64de4295
                      name: 'Classe teste'
                      description: 'Descrição teste'
                      start_date: 02/09/2023
                      end_date: 10/12/2023
                      capacity: 30
                      bookings: []
                    -
                      id: 4e7820c1-ef98-41e7-bbf1-93ae783cd99f
                      name: 'Classe teste'
                      description: 'Descrição teste'
                      start_date: 02/09/2023
                      end_date: 10/12/2023
                      capacity: 30
                      bookings: []
                    -
                      id: cc2c4407-2730-4d8c-b3c0-c1c9cd55332c
                      name: 'Classe teste'
                      description: 'Descrição teste'
                      start_date: 02/09/2023
                      end_date: 10/12/2023
                      capacity: 30
                      bookings: []
                properties:
                  message:
                    type: string
                    example: 'Classes retrieved successfully!'
                  total:
                    type: integer
                    example: 5
                  nextPageUrl:
                    type: string
                    example: ''
                  content:
                    type: array
                    example:
                      -
                        id: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                        name: 'Classe updated'
                        description: 'Descrição teste'
                        start_date: 02/09/2023
                        end_date: 10/12/2023
                        capacity: 30
                        bookings:
                          -
                            id: 0a3aaca2-4435-4d9c-a075-ee90b0ca8f97
                            class_id: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                            name: Gabriel
                            date: 11/11/2023
                          -
                            id: 5b0c85de-e1a6-4876-b409-b1b886588fd1
                            class_id: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                            name: Gabriel
                            date: 11/11/2023
                          -
                            id: bf5c029c-d20a-4635-ad26-9c7b6efa8f26
                            class_id: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                            name: Gabriel
                            date: 11/11/2023
                      -
                        id: a094d309-6974-405b-8559-fe0f4684c92c
                        name: 'Classe teste'
                        description: 'Descrição teste'
                        start_date: 02/09/2023
                        end_date: 10/12/2023
                        capacity: 30
                        bookings: []
                      -
                        id: ee440f38-073a-426f-885d-6a9a64de4295
                        name: 'Classe teste'
                        description: 'Descrição teste'
                        start_date: 02/09/2023
                        end_date: 10/12/2023
                        capacity: 30
                        bookings: []
                      -
                        id: 4e7820c1-ef98-41e7-bbf1-93ae783cd99f
                        name: 'Classe teste'
                        description: 'Descrição teste'
                        start_date: 02/09/2023
                        end_date: 10/12/2023
                        capacity: 30
                        bookings: []
                      -
                        id: cc2c4407-2730-4d8c-b3c0-c1c9cd55332c
                        name: 'Classe teste'
                        description: 'Descrição teste'
                        start_date: 02/09/2023
                        end_date: 10/12/2023
                        capacity: 30
                        bookings: []
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                        name:
                          type: string
                          example: 'Classe updated'
                        description:
                          type: string
                          example: 'Descrição teste'
                        start_date:
                          type: string
                          example: 02/09/2023
                        end_date:
                          type: string
                          example: 10/12/2023
                        capacity:
                          type: integer
                          example: 30
                        bookings:
                          type: array
                          example:
                            -
                              id: 0a3aaca2-4435-4d9c-a075-ee90b0ca8f97
                              class_id: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                              name: Gabriel
                              date: 11/11/2023
                            -
                              id: 5b0c85de-e1a6-4876-b409-b1b886588fd1
                              class_id: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                              name: Gabriel
                              date: 11/11/2023
                            -
                              id: bf5c029c-d20a-4635-ad26-9c7b6efa8f26
                              class_id: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                              name: Gabriel
                              date: 11/11/2023
                          items:
                            type: object
                            properties:
                              id:
                                type: string
                                example: 0a3aaca2-4435-4d9c-a075-ee90b0ca8f97
                              class_id:
                                type: string
                                example: 227d6055-4fe8-4793-93e2-b5efcd4ae262
                              name:
                                type: string
                                example: Gabriel
                              date:
                                type: string
                                example: 11/11/2023
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiClasses
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 100 characters.'
                  example: qnfjubaasuyvihnjutmdnfr
                description:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 100 characters.'
                  example: 'Sequi inventore ut cum dolore rem eveniet vel.'
                start_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-07-10T03:49:13'
                end_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-07-10T03:49:13'
                capacity:
                  type: integer
                  description: ''
                  example: 10
              required:
                - name
                - description
                - start_date
                - end_date
                - capacity
      security: []
  '/api/classes/{id}':
    get:
      summary: ''
      operationId: getApiClassesId
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Contact not found'
                properties:
                  error:
                    type: string
                    example: 'Contact not found'
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiClassesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 100 characters.'
                  example: dy
                description:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 100 characters.'
                  example: 'Et et voluptatem voluptatem.'
                start_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-07-10T03:49:13'
                end_date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-07-10T03:49:13'
                capacity:
                  type: integer
                  description: ''
                  example: 17
      security: []
    delete:
      summary: ''
      operationId: deleteApiClassesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the class.'
        example: est
        required: true
        schema:
          type: string
  '/api/classes/{id}/bookings':
    post:
      summary: ''
      operationId: postApiClassesIdBookings
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 100 characters.'
                  example: jafqtezzpnatcn
                date:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-07-10T03:49:13'
              required:
                - name
                - date
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the class.'
        example: molestiae
        required: true
        schema:
          type: string
  '/api/classes/{id}/bookings/{id}':
    get:
      summary: ''
      operationId: getApiClassesIdBookingsId
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Hello World!'
                properties:
                  message:
                    type: string
                    example: 'Hello World!'
      tags:
        - Endpoints
      security: []
    put:
      summary: ''
      operationId: putApiClassesIdBookingsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    delete:
      summary: ''
      operationId: deleteApiClassesIdBookingsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the class.'
        example: laudantium
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
